---
title: "Data Cleaning"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(lubridate)
library(tidyr)
```


## Load Data
```{r}
# Load data
df_0 <- read.csv('../data/DOHMH_New_York_City_Restaurant_Inspection_Results.csv')
```


## Data cleaning
- change format
- remove missing values
```{r}
# data cleaning
df.clean <- df_0 %>% 
  rename_all(tolower) %>%
  rename(cuisine = cuisine.description) %>%
  mutate(cuisine = str_replace(cuisine, " \\(.*\\)", "")) %>%
  mutate(region = as.character(zipcode)) %>%
  filter(region > 0 & region != 'N/A') %>%
  mutate(format_inspection_date = mdy(inspection.date),
         inspection_year = year(format_inspection_date)) %>%
  filter(inspection_year == 2019 | inspection_year == 2020)
```


## Define functions
```{r}
#================== Text Processing ===================
#https://rstudio-pubs-static.s3.amazonaws.com/408658_512da947714740b99253228f084a08a9.html

to.upper <- function(word){
  string <- strsplit(as.character(word), " ")[[1]]
  s <- paste(substring(string, 1,1), tolower(substring(string, 2)), sep="", collapse=" ")
  str_replace(s, " \\(.*\\)", "")
}

number.to.phone <- function(number){
  first <- substring(number,1,3)
  second <- substring(number, 4,6)
  third <- substring(number, 7, 9)
  paste0("(", first, ") ", second, "-", third)
}

address <- function(building, street, boro, zipcode){
  if(boro == "Manhattan") boro = "New York"
  paste0(building, " ", street, ", ", boro, ", ", "NY ", zipcode)
}


ViolationType <- list(
  "04"= "Evidence of Mice/Roches/Flies",
  "02"= "Food Temperature",
  "06"= "Food Contact Surfaces Not Clean and Sanitized",
  "08"= "Pest Related Facility Use",
  "10"= "Non-food Contact Surfaces/Facility Improperly Constructed")

```


## Data cleaning: text cleaning
```{r}
df <- df.clean %>%
  filter(grade %in% c('A', 'B', 'C', 'Z', 'P', 'N') &
           !is.na(latitude) & !is.na(longitude)) %>%
  mutate(dba = map_chr(dba, function(x) to.upper(x)),
         building = map_chr(building, function(x) to.upper(x)),
         street = map_chr(street, function(x) to.upper(x)),
         phone = map_chr(phone, function(x) number.to.phone(x)),
         boro = as.character(boro),
         address = pmap(list(building, street, boro, zipcode), 
                            function(x, y, z, w) address(x, y, z, w))) %>%
  mutate(violation.short.desp = ViolationType[substring(violation.code, 0, 2)])

```


## Save the cleaned data
```{r}
save(df, file="../output/df.RData")
```

